### ISSUE TITLE
How to verify assertion response

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/WebAuthntine#4]
I noticed that in order to be able to verify an assertion, an authenticator object needs to be passed.
The idea is that the counter of the authenticator needs to be checked, which is great. However, how can I know in advance which authenticator the user chose to authenticate, when multiple authenticators are available to a user?
It would be great if an array of authenticators would be supported. The selected authenticator would then be picked from that array based on `response.base64CredentialID`.

**Comment by MasterKale** [comment]
**Server's `generateAssertionOptions()`** method already accepts a list of credential ID's - check out [line 20](https://github.com/MasterKale/WebAuthntine/blob/master/packages/server/src/assertion/generateAssertionOptions.ts#L20). The array of the user's attested credential ID's gets massaged into a correctly-shaped object before being passed into `navigator.credentials.get()` via **browser's `startAssertion()`** method.

Then, on [line 56] of `startAssertion()`, `base64CredentialID` is returned because, as you point out, the server would otherwise have no idea which credential from the list it should check the returned counter value against.

Unless you're referring to how the server should know which device to pass into `verifyAssertionResponse()`? I try to explain that in [the example, on line 119](https://github.com/MasterKale/WebAuthntine/blob/master/example/index.js#L119). I think the answer is that the server queries the DB for a device with an ID of `response.base64CredentialID`.

**Comment by P4sca1** [comment]
Ah, I missed that you get that in `response.base64CredentialID` from the browser package.
Your example made that clear. Thanks for the quick help! :)
