### ISSUE TITLE
Unexpected attestation challenge

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/WebAuthntine#7]
I just tested the challenge check introduced in #5 and always get the unexpected attestation challenge error. Maybe it is something on my end.

Example error: `Unexpected attestation challenge "MFpYWTliNDk0Vzd4UGJxV05tci9MM0JQVElodW5IRGM1OURVN05odDd2VT0", expected "0ZXY9b494W7xPbqWNmr/L3BPTIhunHDc59DU7Nht7vU="`

The expected challenge is correct. The client also gets the expected challenge correctly from the server in `publicKey.challenge`. 

This is how I create the challenge: `randomBytes(32).toString('base64')`.

**Comment by MasterKale** [comment]
Are you using server@0.2.1? I had to make a tweak after #5 because it turns out the parsed client data JSON was giving back challenges in base64. See commit https://github.com/MasterKale/WebAuthntine/commit/b2d897ff93444b5e25b3e26892b627f2b771b5bf.

Out of curiosity I hand-converted the challenge above and it did indeed equal the expected value:

```js
Buffer.from(
  'MFpYWTliNDk0Vzd4UGJxV05tci9MM0JQVElodW5IRGM1OURVN05odDd2VT0', 
  'base64',
).toString('ascii'); // -> '0ZXY9b494W7xPbqWNmr/L3BPTIhunHDc59DU7Nht7vU='
```

**Comment by P4sca1** [comment]
@MasterKale Going to try out 0.2.1 now. Is it intended that only `@webauthntine/server` got bumped? Because normally lerna bumps all versions even if only one package changed if independent versioning is not explicitly enabled.

**Comment by P4sca1** [comment]
Can confirm that the challenge is now correctly checked and the error is gone.

**Comment by MasterKale** [comment]
That's what I thought too - I explicitly _didn't_ set independent versions because I wanted everything incremented in lockstep.

What lerna's been doing is syncing package versions if anything changed in a package between publications. One time **browser** went from 0.1.4 to 0.1.6 because 0.1.5 only involved changes to **server**. 0.1.6 included changes to both, so both package versions got updated...

**Comment by P4sca1** [comment]
Maybe yesterdays lerna update broke that behaviour?
Which command are you using for publish?

**Comment by MasterKale** [comment]
I use the basic `npx lerna publish` command 🤷‍♂️  It otherwise works fine to get npm updated, so I've just chalked this up to one of the many idiosyncracies of Lerna 😬
